### ISSUE TITLE
Line plot masks non-daily reporting increments

### ISSUE THREAD

**Issue by trvrb** [colinmegill/ebola#18]
Drawing a line masks the data.  Here are the raw points:

![curve](https://cloud.githubusercontent.com/assets/1176109/4007444/9c35f668-29c4-11e4-8781-6fb546e18ab2.png)

You can see that there are often stretches of ~5 days, where counts of cumulative cases do not change.  This is not from a lack of real cases, it's just due to reporting increments.  I think it would be more accurate to show points (and a line connecting them) only for days in which there is an increase in count.  This would be the first point in these stretches.

**Comment by colinmegill** [comment]
Ah, @trvrb I obviously missed this in my last reply - we're on exactly the same page. I'll take care of that.
