### ISSUE TITLE
Can we get this online?

### ISSUE THREAD

**Issue by trvrb** [colinmegill/ebola#22]
I know ebolastats.com is live.  With a small bit of cleanup this can be promoted and actually be useful to people.

**Comment by colinmegill** [comment]
Trevor,

Yes - I've been feeling it too. We've been swamped with priorities at pol.is
- we'll get it back up.

Thanks for pushing us,

**Comment by trvrb** [comment]
No worries.  Just want to show off your hard work on this.

**Comment by colinmegill** [comment]
@trvrb fixed. Thanks again for pushing me.

**Comment by trvrb** [comment]
Fantastic.  Can I start tweeting ebolastats.com?

**Comment by colinmegill** [comment]
Indeed. Tweet away.
