### ISSUE TITLE
visual for the top of the site?

### ISSUE THREAD

**Issue by colinmegill** [colinmegill/ebola#4]

**Comment by metasoarous** [comment]
How about a play on something like this

![image](https://cloud.githubusercontent.com/assets/88556/3947122/a9e02656-2683-11e4-9772-2168ab7aabe6.png)

Its a visual motif that I think a lot of people are very familiar with. Could integrate some data-vizy fancy looking what-haveyou as well perhaps.

**Comment by metasoarous** [comment]
I could vectorize that and clean up a bit as a bit of core visual language.

**Comment by colinmegill** [comment]
Graphs & networks for dispersion are also appropriate, as is geography

**Comment by metasoarous** [comment]
@paulathevalley - Just added a rough vectorization of the image above in case you want to use that somewhere in the top banner.
